// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createthecategoryproductsellerstables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createthecategoryproductsellerstables));
        
        string IMigrationMetadata.Id
        {
            get { return "202103301531454_create the category, product, sellers tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
